spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ceobthk@gmail.com
    password: 2020@Ipda@gm
    properties:
      mail:
        smtp:
          starttls.enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

